# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FamilyDiary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FamilyDiary

  pod 'Firebase/Core' 
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'FamilyDiaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FamilyDiaryUITests' do
    # Pods for testing
  end

end
