# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sand_FamilyDiary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sand_FamilyDiary

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'sand_FamilyDiaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sand_FamilyDiaryUITests' do
    # Pods for testing
  end

end
